// Dummy data for development — matches the real database structure
// Replace with Prisma queries once the DB is connected

export const dummyCategories = [
  {
    id: "cat-1",
    name: "কাঁথা",
    slug: "katha",
    imageUrl: "/uploads/categories/katha.jpg",
    isFeatured: true,
    sortOrder: 1,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "cat-2",
    name: "চাদর",
    slug: "chador",
    imageUrl: "/uploads/categories/chador.jpg",
    isFeatured: true,
    sortOrder: 2,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "cat-3",
    name: "কম্বল",
    slug: "kambal",
    imageUrl: "/uploads/categories/kambal.jpg",
    isFeatured: true,
    sortOrder: 3,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "cat-4",
    name: "নকশিকাঁথা",
    slug: "nakshi-katha",
    imageUrl: "/uploads/categories/nakshi-katha.jpg",
    isFeatured: true,
    sortOrder: 4,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "cat-5",
    name: "মসলিন",
    slug: "muslin",
    imageUrl: "/uploads/categories/muslin.jpg",
    isFeatured: false,
    sortOrder: 5,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
];

export const dummyProducts = [
  {
    id: "prod-1",
    title: "হাতে বোনা রাজশাহী সিল্ক কাঁথা",
    slug: "hath-bona-rajshahi-silk-katha",
    description:
      "রাজশাহীর বিখ্যাত সিল্ক সুতা দিয়ে হাতে বোনা এই কাঁথা একটি অনন্য শিল্পকর্ম। প্রতিটি কাঁথায় রয়েছে ঐতিহ্যবাহী বাংলার নকশা। বছরের পর বছর ব্যবহারযোগ্য এই কাঁথা পরিবারের জন্য একটি বিশেষ উপহার।",
    price: 2500,
    compareAtPrice: 3200,
    stock: 15,
    categoryId: "cat-1",
    isFeatured: true,
    isBestSelling: true,
    status: "ACTIVE",
    sku: "KTH-001",
    tags: ["কাঁথা", "সিল্ক", "রাজশাহী", "হস্তশিল্প"],
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
    category: { id: "cat-1", name: "কাঁথা", slug: "katha" },
    images: [
      {
        id: "img-1",
        productId: "prod-1",
        imageUrl: "/uploads/products/katha-1.jpg",
        sortOrder: 0,
        altText: "রাজশাহী সিল্ক কাঁথা",
      },
    ],
  },
  {
    id: "prod-2",
    title: "নকশিকাঁথা — ফুল ও পাখির ডিজাইন",
    slug: "nakshi-katha-ful-pakhi",
    description:
      "ফুল ও পাখির অপূর্ব নকশায় তৈরি এই নকশিকাঁথা বাংলাদেশের ঐতিহ্যবাহী শিল্পকলার এক মনোমুগ্ধকর প্রতিফলন। দক্ষ কারিগরদের হাতে সুতার বুনন এবং রঙের খেলায় এটি পরিণত হয়েছে একটি শিল্পকর্মে।",
    price: 3800,
    compareAtPrice: 4500,
    stock: 8,
    categoryId: "cat-4",
    isFeatured: true,
    isBestSelling: true,
    status: "ACTIVE",
    sku: "NKK-001",
    tags: ["নকশিকাঁথা", "ফুল", "পাখি", "হস্তশিল্প"],
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
    category: { id: "cat-4", name: "নকশিকাঁথা", slug: "nakshi-katha" },
    images: [
      {
        id: "img-2",
        productId: "prod-2",
        imageUrl: "/uploads/products/nakshi-katha-1.jpg",
        sortOrder: 0,
        altText: "নকশিকাঁথা ফুল ও পাখি",
      },
    ],
  },
  {
    id: "prod-3",
    title: "সুতি চাদর — ট্র্যাডিশনাল স্ট্রাইপ",
    slug: "suti-chador-traditional-stripe",
    description:
      "খাঁটি সুতা দিয়ে তৈরি এই ট্র্যাডিশনাল স্ট্রাইপ চাদর গরমের দিনে আরামদায়ক সঙ্গী। হালকা ওজনের এই চাদর শরীরকে ঠান্ডা রাখে এবং ঐতিহ্যবাহী নকশায় সাজানো।",
    price: 1200,
    compareAtPrice: 1500,
    stock: 25,
    categoryId: "cat-2",
    isFeatured: true,
    isBestSelling: false,
    status: "ACTIVE",
    sku: "CHD-001",
    tags: ["চাদর", "সুতি", "স্ট্রাইপ"],
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-02-01"),
    category: { id: "cat-2", name: "চাদর", slug: "chador" },
    images: [
      {
        id: "img-3",
        productId: "prod-3",
        imageUrl: "/uploads/products/chador-1.jpg",
        sortOrder: 0,
        altText: "সুতি চাদর স্ট্রাইপ",
      },
    ],
  },
  {
    id: "prod-4",
    title: "শীতকালীন উলের কম্বল",
    slug: "shitkalin-uler-kambal",
    description:
      "কড়া শীতেও উষ্ণ রাখবে এই উলের কম্বল। উচ্চমানের উল দিয়ে তৈরি এই কম্বল টেকসই এবং নরম। পরিবারের সবার জন্য উপযুক্ত।",
    price: 4200,
    compareAtPrice: 5000,
    stock: 12,
    categoryId: "cat-3",
    isFeatured: false,
    isBestSelling: true,
    status: "ACTIVE",
    sku: "KMB-001",
    tags: ["কম্বল", "উল", "শীতকালীন"],
    createdAt: new Date("2024-02-10"),
    updatedAt: new Date("2024-02-10"),
    category: { id: "cat-3", name: "কম্বল", slug: "kambal" },
    images: [
      {
        id: "img-4",
        productId: "prod-4",
        imageUrl: "/uploads/products/kambal-1.jpg",
        sortOrder: 0,
        altText: "উলের কম্বল",
      },
    ],
  },
  {
    id: "prod-5",
    title: "বাংলাদেশি মসলিন চাদর",
    slug: "bangladeshi-muslin-chador",
    description:
      "বাংলাদেশের ঐতিহ্যবাহী মসলিন কাপড়ে তৈরি এই চাদর অত্যন্ত মসৃণ এবং আরামদায়ক। ঢাকাই মসলিনের বিশেষত্ব হলো এর অসাধারণ সূক্ষ্মতা।",
    price: 5500,
    compareAtPrice: 6500,
    stock: 6,
    categoryId: "cat-5",
    isFeatured: false,
    isBestSelling: false,
    status: "ACTIVE",
    sku: "MSL-001",
    tags: ["মসলিন", "চাদর", "ঢাকাই"],
    createdAt: new Date("2024-02-15"),
    updatedAt: new Date("2024-02-15"),
    category: { id: "cat-5", name: "মসলিন", slug: "muslin" },
    images: [
      {
        id: "img-5",
        productId: "prod-5",
        imageUrl: "/uploads/products/muslin-1.jpg",
        sortOrder: 0,
        altText: "মসলিন চাদর",
      },
    ],
  },
  {
    id: "prod-6",
    title: "শিশু কাঁথা — সফট কটন",
    slug: "shishu-katha-soft-cotton",
    description:
      "শিশুর কোমল ত্বকের কথা মাথায় রেখে তৈরি এই সফট কটন কাঁথা। অর্গানিক সুতায় তৈরি এবং কোনো ক্ষতিকর রং ব্যবহার করা হয়নি। নবজাতক থেকে ৩ বছর পর্যন্ত উপযুক্ত।",
    price: 1800,
    compareAtPrice: 2200,
    stock: 20,
    categoryId: "cat-1",
    isFeatured: false,
    isBestSelling: false,
    status: "ACTIVE",
    sku: "KTH-002",
    tags: ["কাঁথা", "শিশু", "কটন", "অর্গানিক"],
    createdAt: new Date("2024-02-20"),
    updatedAt: new Date("2024-02-20"),
    category: { id: "cat-1", name: "কাঁথা", slug: "katha" },
    images: [
      {
        id: "img-6",
        productId: "prod-6",
        imageUrl: "/uploads/products/baby-katha.jpg",
        sortOrder: 0,
        altText: "শিশু কাঁথা",
      },
    ],
  },
  {
    id: "prod-7",
    title: "জামদানি চাদর — ক্লাসিক ডিজাইন",
    slug: "jamdani-chador-classic",
    description:
      "জামদানি শিল্পের অনুপ্রেরণায় তৈরি এই চাদরটি বাংলার ঐতিহ্যকে আধুনিকতার সাথে মিলিয়ে তৈরি। বিয়ে বা উৎসবের জন্য আদর্শ উপহার।",
    price: 3200,
    compareAtPrice: 4000,
    stock: 10,
    categoryId: "cat-2",
    isFeatured: false,
    isBestSelling: false,
    status: "ACTIVE",
    sku: "CHD-002",
    tags: ["চাদর", "জামদানি", "উৎসব"],
    createdAt: new Date("2024-03-01"),
    updatedAt: new Date("2024-03-01"),
    category: { id: "cat-2", name: "চাদর", slug: "chador" },
    images: [
      {
        id: "img-7",
        productId: "prod-7",
        imageUrl: "/uploads/products/jamdani-chador.jpg",
        sortOrder: 0,
        altText: "জামদানি চাদর",
      },
    ],
  },
  {
    id: "prod-8",
    title: "নকশিকাঁথা — লতাপাতার ডিজাইন",
    slug: "nakshi-katha-lata-pata",
    description:
      "লতাপাতার সুন্দর নকশায় তৈরি এই নকশিকাঁথা ঘরের সৌন্দর্য বৃদ্ধি করে। ওয়াল হ্যাংগিং হিসেবে বা বিছানার চাদর হিসেবে ব্যবহার করা যায়।",
    price: 4500,
    compareAtPrice: null,
    stock: 5,
    categoryId: "cat-4",
    isFeatured: false,
    isBestSelling: false,
    status: "ACTIVE",
    sku: "NKK-002",
    tags: ["নকশিকাঁথা", "লতাপাতা", "ওয়াল হ্যাংগিং"],
    createdAt: new Date("2024-03-10"),
    updatedAt: new Date("2024-03-10"),
    category: { id: "cat-4", name: "নকশিকাঁথা", slug: "nakshi-katha" },
    images: [
      {
        id: "img-8",
        productId: "prod-8",
        imageUrl: "/uploads/products/nakshi-katha-2.jpg",
        sortOrder: 0,
        altText: "নকশিকাঁথা লতাপাতা",
      },
    ],
  },
];

export const dummyReviews = [
  {
    id: "rev-1",
    name: "রাহেলা বেগম",
    title: "অসাধারণ মানের পণ্য",
    rating: 5,
    content:
      "শিল্পেরহাট থেকে কেনা কাঁথাটি সত্যিই অসাধারণ। হাতের কাজ এত সুন্দর যে বিশ্বাস হচ্ছিল না। দাম দিয়ে সম্পূর্ণ মূল্য পেয়েছি। পরিবারের সবাই খুব পছন্দ করেছে।",
    avatarUrl: null,
    role: "ঢাকা, বাংলাদেশ",
    isVisible: true,
    sortOrder: 1,
    createdAt: new Date("2024-03-01"),
    updatedAt: new Date("2024-03-01"),
  },
  {
    id: "rev-2",
    name: "মো. করিম হোসেন",
    title: "দ্রুত ডেলিভারি এবং চমৎকার প্যাকেজিং",
    rating: 5,
    content:
      "অর্ডার দেওয়ার মাত্র ২ দিনের মধ্যে পণ্য পেয়েছি। প্যাকেজিং খুব সুন্দর ছিল। নকশিকাঁথাটি আমার মায়ের জন্য উপহার হিসেবে কিনেছিলাম, তিনি দেখে মুগ্ধ হয়েছেন।",
    avatarUrl: null,
    role: "চট্টগ্রাম, বাংলাদেশ",
    isVisible: true,
    sortOrder: 2,
    createdAt: new Date("2024-03-05"),
    updatedAt: new Date("2024-03-05"),
  },
  {
    id: "rev-3",
    name: "সুমাইয়া আক্তার",
    title: "বিশ্বস্ত অনলাইন শপ",
    rating: 4,
    content:
      "অনলাইনে অনেক জায়গা থেকে কেনাকাটা করেছি কিন্তু শিল্পেরহাটের মতো বিশ্বস্ত আর কোথাও পাইনি। পণ্যের মান এবং কাস্টমার সার্ভিস দুটোই চমৎকার। আবার কিনব।",
    avatarUrl: null,
    role: "রাজশাহী, বাংলাদেশ",
    isVisible: true,
    sortOrder: 3,
    createdAt: new Date("2024-03-10"),
    updatedAt: new Date("2024-03-10"),
  },
  {
    id: "rev-4",
    name: "তানিয়া ইসলাম",
    title: "ঐতিহ্যবাহী পণ্যের সেরা সংগ্রহ",
    rating: 5,
    content:
      "দেশীয় হস্তশিল্পের এত সুন্দর সংগ্রহ আর কোথাও পাইনি। প্রতিটি পণ্যে কারিগরের পরিশ্রম ও দক্ষতা স্পষ্ট। এই রকম দেশীয় শিল্পকে সমর্থন করা উচিত।",
    avatarUrl: null,
    role: "সিলেট, বাংলাদেশ",
    isVisible: true,
    sortOrder: 4,
    createdAt: new Date("2024-03-15"),
    updatedAt: new Date("2024-03-15"),
  },
  {
    id: "rev-5",
    name: "আবু সাঈদ",
    title: "কাঁথার মান অতুলনীয়",
    rating: 5,
    content:
      "শীতকালীন কম্বলটি কিনেছিলাম। কোয়ালিটি দেখে অবাক হয়ে গেছি। এত ভালো মানের পণ্য এই দামে কোথাও পাওয়া যায় না। পুরো পরিবারের জন্য আরও কিনব।",
    avatarUrl: null,
    role: "খুলনা, বাংলাদেশ",
    isVisible: true,
    sortOrder: 5,
    createdAt: new Date("2024-03-20"),
    updatedAt: new Date("2024-03-20"),
  },
];

export const dummyBanners = [
  {
    id: "ban-1",
    title: "বাংলার ঐতিহ্যবাহী হস্তশিল্প",
    subtitle: "হাতে বোনা কাঁথা, চাদর ও কম্বলের বিশাল সংগ্রহ",
    imageUrl: "/uploads/banners/banner-1.jpg",
    mobileImageUrl: "/uploads/banners/banner-1-mobile.jpg",
    buttonText: "এখনই কিনুন",
    buttonLink: "/shop",
    sortOrder: 1,
    isActive: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
];

export const dummySiteSettings = {
  id: "settings-1",
  siteName: "শিল্পেরহাট",
  logoUrl: null,
  faviconUrl: null,
  footerCopyright: "© ২০২৪ শিল্পেরহাট। সর্বস্বত্ব সংরক্ষিত।",
  whatsappNumber: "01700000000",
  socialLinks: {
    facebook: "https://facebook.com/shilperhaat",
    instagram: "https://instagram.com/shilperhaat",
  },
  deliveryCharge: 80,
  freeDeliveryMin: 2000,
  updatedAt: new Date("2024-01-01"),
};
