// Dummy data for development — matches the real database structure
// Replace with Prisma queries once the DB is connected

export const dummyCategories = [
  {
    id: "cat-1",
    name: "Katha",
    slug: "katha",
    imageUrl: "https://picsum.photos/seed/katha-weave/500/500",
    isFeatured: true,
    sortOrder: 1,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "cat-4",
    name: "Nakshi Katha",
    slug: "nakshi-katha",
    imageUrl: "https://picsum.photos/seed/nakshi-embroidery/500/500",
    isFeatured: true,
    sortOrder: 2,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "cat-2",
    name: "Chadar",
    slug: "chador",
    imageUrl: "https://picsum.photos/seed/chadar-fabric/500/500",
    isFeatured: true,
    sortOrder: 3,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "cat-3",
    name: "Blanket",
    slug: "kambal",
    imageUrl: "https://picsum.photos/seed/wool-blanket/500/500",
    isFeatured: true,
    sortOrder: 4,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "cat-5",
    name: "Muslin",
    slug: "muslin",
    imageUrl: "https://picsum.photos/seed/muslin-cloth/500/500",
    isFeatured: true,
    sortOrder: 5,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "cat-6",
    name: "Jamdani",
    slug: "jamdani",
    imageUrl: "https://picsum.photos/seed/jamdani-weave/500/500",
    isFeatured: true,
    sortOrder: 6,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "cat-7",
    name: "Gamcha",
    slug: "gamcha",
    imageUrl: "https://picsum.photos/seed/gamcha-stripe/500/500",
    isFeatured: true,
    sortOrder: 7,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "cat-8",
    name: "New Arrivals",
    slug: "new-arrivals",
    imageUrl: "https://picsum.photos/seed/new-arrivals-textile/500/500",
    isFeatured: true,
    sortOrder: 8,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
];

export const dummyProducts = [
  {
    id: "prod-1",
    title: "Hand-Woven Rajshahi Silk Katha",
    slug: "hand-woven-rajshahi-silk-katha",
    description:
      "This hand-woven katha made from the famous Rajshahi silk is a unique work of art. Each piece features traditional Bengali patterns. Durable for years, it makes a wonderful gift for the whole family.",
    price: 2500,
    compareAtPrice: 3200,
    stock: 15,
    categoryId: "cat-1",
    isFeatured: true,
    isBestSelling: true,
    status: "ACTIVE",
    sku: "KTH-001",
    tags: ["katha", "silk", "rajshahi", "handcraft"],
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
    category: { id: "cat-1", name: "Katha", slug: "katha" },
    images: [
      { id: "img-1a", productId: "prod-1", imageUrl: "https://picsum.photos/seed/silk-katha-1/600/600",   sortOrder: 0, altText: "Rajshahi Silk Katha — Front" },
      { id: "img-1b", productId: "prod-1", imageUrl: "https://picsum.photos/seed/silk-katha-1b/600/600",  sortOrder: 1, altText: "Rajshahi Silk Katha — Detail" },
      { id: "img-1c", productId: "prod-1", imageUrl: "https://picsum.photos/seed/silk-katha-1c/600/600",  sortOrder: 2, altText: "Rajshahi Silk Katha — Pattern" },
      { id: "img-1d", productId: "prod-1", imageUrl: "https://picsum.photos/seed/silk-katha-1d/600/600",  sortOrder: 3, altText: "Rajshahi Silk Katha — Full view" },
    ],
  },
  {
    id: "prod-2",
    title: "Nakshi Katha — Floral & Bird Design",
    slug: "nakshi-katha-floral-bird",
    description:
      "This Nakshi Katha adorned with intricate floral and bird motifs is a captivating reflection of Bangladesh's traditional art. The skilled artisans' threadwork and play of colors have transformed it into a masterpiece.",
    price: 3800,
    compareAtPrice: 4500,
    stock: 8,
    categoryId: "cat-4",
    isFeatured: true,
    isBestSelling: true,
    status: "ACTIVE",
    sku: "NKK-001",
    tags: ["nakshi-katha", "floral", "bird", "handcraft"],
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
    category: { id: "cat-4", name: "Nakshi Katha", slug: "nakshi-katha" },
    images: [
      { id: "img-2a", productId: "prod-2", imageUrl: "https://picsum.photos/seed/nakshi-floral-2/600/600",  sortOrder: 0, altText: "Nakshi Katha Floral Bird — Front" },
      { id: "img-2b", productId: "prod-2", imageUrl: "https://picsum.photos/seed/nakshi-floral-2b/600/600", sortOrder: 1, altText: "Nakshi Katha — Bird motif" },
      { id: "img-2c", productId: "prod-2", imageUrl: "https://picsum.photos/seed/nakshi-floral-2c/600/600", sortOrder: 2, altText: "Nakshi Katha — Thread detail" },
      { id: "img-2d", productId: "prod-2", imageUrl: "https://picsum.photos/seed/nakshi-floral-2d/600/600", sortOrder: 3, altText: "Nakshi Katha — Full view" },
    ],
  },
  {
    id: "prod-3",
    title: "Cotton Chadar — Traditional Stripe",
    slug: "cotton-chadar-traditional-stripe",
    description:
      "Made from pure cotton thread, this traditional stripe chadar is the perfect companion for warm days. Lightweight and breathable, it keeps you cool while showcasing traditional patterns.",
    price: 1200,
    compareAtPrice: 1500,
    stock: 25,
    categoryId: "cat-2",
    isFeatured: true,
    isBestSelling: false,
    status: "ACTIVE",
    sku: "CHD-001",
    tags: ["chadar", "cotton", "stripe"],
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-02-01"),
    category: { id: "cat-2", name: "Chadar", slug: "chador" },
    images: [
      { id: "img-3a", productId: "prod-3", imageUrl: "https://picsum.photos/seed/cotton-chadar-3/600/600",  sortOrder: 0, altText: "Cotton Chadar Stripe — Front" },
      { id: "img-3b", productId: "prod-3", imageUrl: "https://picsum.photos/seed/cotton-chadar-3b/600/600", sortOrder: 1, altText: "Cotton Chadar — Stripe pattern" },
      { id: "img-3c", productId: "prod-3", imageUrl: "https://picsum.photos/seed/cotton-chadar-3c/600/600", sortOrder: 2, altText: "Cotton Chadar — Fabric texture" },
    ],
  },
  {
    id: "prod-4",
    title: "Winter Wool Blanket",
    slug: "winter-wool-blanket",
    description:
      "This wool blanket will keep you warm even in the harshest winters. Made from premium-quality wool, it is durable and soft. Suitable for the whole family.",
    price: 4200,
    compareAtPrice: 5000,
    stock: 12,
    categoryId: "cat-3",
    isFeatured: false,
    isBestSelling: true,
    status: "ACTIVE",
    sku: "KMB-001",
    tags: ["blanket", "wool", "winter"],
    createdAt: new Date("2024-02-10"),
    updatedAt: new Date("2024-02-10"),
    category: { id: "cat-3", name: "Blanket", slug: "kambal" },
    images: [
      { id: "img-4a", productId: "prod-4", imageUrl: "https://picsum.photos/seed/wool-blanket-4/600/600",  sortOrder: 0, altText: "Winter Wool Blanket — Front" },
      { id: "img-4b", productId: "prod-4", imageUrl: "https://picsum.photos/seed/wool-blanket-4b/600/600", sortOrder: 1, altText: "Winter Wool Blanket — Folded" },
      { id: "img-4c", productId: "prod-4", imageUrl: "https://picsum.photos/seed/wool-blanket-4c/600/600", sortOrder: 2, altText: "Winter Wool Blanket — Detail" },
      { id: "img-4d", productId: "prod-4", imageUrl: "https://picsum.photos/seed/wool-blanket-4d/600/600", sortOrder: 3, altText: "Winter Wool Blanket — In use" },
    ],
  },
  {
    id: "prod-5",
    title: "Bangladeshi Muslin Chadar",
    slug: "bangladeshi-muslin-chadar",
    description:
      "This chadar made from Bangladesh's traditional muslin fabric is extremely smooth and comfortable. Dhaka muslin is renowned for its extraordinary fineness and delicacy.",
    price: 5500,
    compareAtPrice: 6500,
    stock: 6,
    categoryId: "cat-5",
    isFeatured: false,
    isBestSelling: false,
    status: "ACTIVE",
    sku: "MSL-001",
    tags: ["muslin", "chadar", "dhaka"],
    createdAt: new Date("2024-02-15"),
    updatedAt: new Date("2024-02-15"),
    category: { id: "cat-5", name: "Muslin", slug: "muslin" },
    images: [
      { id: "img-5a", productId: "prod-5", imageUrl: "https://picsum.photos/seed/muslin-chadar-5/600/600",  sortOrder: 0, altText: "Bangladeshi Muslin Chadar — Front" },
      { id: "img-5b", productId: "prod-5", imageUrl: "https://picsum.photos/seed/muslin-chadar-5b/600/600", sortOrder: 1, altText: "Muslin Chadar — Weave detail" },
      { id: "img-5c", productId: "prod-5", imageUrl: "https://picsum.photos/seed/muslin-chadar-5c/600/600", sortOrder: 2, altText: "Muslin Chadar — Draped" },
    ],
  },
  {
    id: "prod-6",
    title: "Baby Katha — Soft Cotton",
    slug: "baby-katha-soft-cotton",
    description:
      "This soft cotton katha is crafted with baby's delicate skin in mind. Made from organic thread with no harmful dyes. Suitable from newborn to 3 years.",
    price: 1800,
    compareAtPrice: 2200,
    stock: 20,
    categoryId: "cat-1",
    isFeatured: false,
    isBestSelling: false,
    status: "ACTIVE",
    sku: "KTH-002",
    tags: ["katha", "baby", "cotton", "organic"],
    createdAt: new Date("2024-02-20"),
    updatedAt: new Date("2024-02-20"),
    category: { id: "cat-1", name: "Katha", slug: "katha" },
    images: [
      { id: "img-6a", productId: "prod-6", imageUrl: "https://picsum.photos/seed/baby-katha-6/600/600",  sortOrder: 0, altText: "Baby Katha — Front" },
      { id: "img-6b", productId: "prod-6", imageUrl: "https://picsum.photos/seed/baby-katha-6b/600/600", sortOrder: 1, altText: "Baby Katha — Soft texture" },
      { id: "img-6c", productId: "prod-6", imageUrl: "https://picsum.photos/seed/baby-katha-6c/600/600", sortOrder: 2, altText: "Baby Katha — Pattern detail" },
    ],
  },
  {
    id: "prod-7",
    title: "Jamdani Chadar — Classic Design",
    slug: "jamdani-chadar-classic",
    description:
      "Inspired by the Jamdani weaving tradition, this chadar blends Bengali heritage with modern aesthetics. An ideal gift for weddings or special occasions.",
    price: 3200,
    compareAtPrice: 4000,
    stock: 10,
    categoryId: "cat-2",
    isFeatured: false,
    isBestSelling: false,
    status: "ACTIVE",
    sku: "CHD-002",
    tags: ["chadar", "jamdani", "festive"],
    createdAt: new Date("2024-03-01"),
    updatedAt: new Date("2024-03-01"),
    category: { id: "cat-2", name: "Chadar", slug: "chador" },
    images: [
      { id: "img-7a", productId: "prod-7", imageUrl: "https://picsum.photos/seed/jamdani-chadar-7/600/600",  sortOrder: 0, altText: "Jamdani Chadar — Front" },
      { id: "img-7b", productId: "prod-7", imageUrl: "https://picsum.photos/seed/jamdani-chadar-7b/600/600", sortOrder: 1, altText: "Jamdani Chadar — Weave motif" },
      { id: "img-7c", productId: "prod-7", imageUrl: "https://picsum.photos/seed/jamdani-chadar-7c/600/600", sortOrder: 2, altText: "Jamdani Chadar — Heritage detail" },
    ],
  },
  {
    id: "prod-8",
    title: "Nakshi Katha — Floral Vine Design",
    slug: "nakshi-katha-floral-vine",
    description:
      "This Nakshi Katha with beautiful floral vine patterns enhances the beauty of any room. Can be used as wall hanging or as a bed cover.",
    price: 4500,
    compareAtPrice: null,
    stock: 5,
    categoryId: "cat-4",
    isFeatured: false,
    isBestSelling: false,
    status: "ACTIVE",
    sku: "NKK-002",
    tags: ["nakshi-katha", "floral-vine", "wall-hanging"],
    createdAt: new Date("2024-03-10"),
    updatedAt: new Date("2024-03-10"),
    category: { id: "cat-4", name: "Nakshi Katha", slug: "nakshi-katha" },
    images: [
      { id: "img-8a", productId: "prod-8", imageUrl: "https://picsum.photos/seed/nakshi-vine-8/600/600",  sortOrder: 0, altText: "Nakshi Katha Vine — Front" },
      { id: "img-8b", productId: "prod-8", imageUrl: "https://picsum.photos/seed/nakshi-vine-8b/600/600", sortOrder: 1, altText: "Nakshi Katha — Vine motif" },
      { id: "img-8c", productId: "prod-8", imageUrl: "https://picsum.photos/seed/nakshi-vine-8c/600/600", sortOrder: 2, altText: "Nakshi Katha — Thread work" },
      { id: "img-8d", productId: "prod-8", imageUrl: "https://picsum.photos/seed/nakshi-vine-8d/600/600", sortOrder: 3, altText: "Nakshi Katha — Wall display" },
    ],
  },

  /* ── Additional Katha products (cat-1) ── */
  {
    id: "prod-9",
    title: "Double-Layer Cotton Katha",
    slug: "double-layer-cotton-katha",
    description: "Two layers of soft cotton hand-stitched together with intricate running patterns. Ideal for all seasons — warm in winter, light in summer.",
    price: 2100,
    compareAtPrice: 2600,
    stock: 18,
    categoryId: "cat-1",
    isFeatured: false,
    isBestSelling: false,
    status: "ACTIVE",
    sku: "KTH-003",
    tags: ["katha", "cotton", "double-layer"],
    createdAt: new Date("2024-04-01"),
    updatedAt: new Date("2024-04-01"),
    category: { id: "cat-1", name: "Katha", slug: "katha" },
    images: [
      { id: "img-9a", productId: "prod-9", imageUrl: "https://picsum.photos/seed/cotton-katha-9/600/600", sortOrder: 0, altText: "Double-Layer Katha — Front" },
      { id: "img-9b", productId: "prod-9", imageUrl: "https://picsum.photos/seed/cotton-katha-9b/600/600", sortOrder: 1, altText: "Double-Layer Katha — Texture" },
    ],
  },
  {
    id: "prod-10",
    title: "Premium Kantha Quilt — Geometric",
    slug: "premium-kantha-quilt-geometric",
    description: "Hand-stitched geometric patterns on premium cotton fabric. This kantha quilt brings timeless Bangladeshi artistry to your home.",
    price: 3100,
    compareAtPrice: 3800,
    stock: 9,
    categoryId: "cat-1",
    isFeatured: false,
    isBestSelling: false,
    status: "ACTIVE",
    sku: "KTH-004",
    tags: ["katha", "geometric", "quilt"],
    createdAt: new Date("2024-04-05"),
    updatedAt: new Date("2024-04-05"),
    category: { id: "cat-1", name: "Katha", slug: "katha" },
    images: [
      { id: "img-10a", productId: "prod-10", imageUrl: "https://picsum.photos/seed/geometric-katha-10/600/600", sortOrder: 0, altText: "Geometric Kantha — Front" },
      { id: "img-10b", productId: "prod-10", imageUrl: "https://picsum.photos/seed/geometric-katha-10b/600/600", sortOrder: 1, altText: "Geometric Kantha — Pattern" },
    ],
  },

  /* ── Additional Nakshi Katha products (cat-4) ── */
  {
    id: "prod-11",
    title: "Nakshi Katha — Peacock Motif",
    slug: "nakshi-katha-peacock-motif",
    description: "A masterpiece featuring stunning peacock motifs hand-embroidered by skilled artisans of Jamalpur. Each stitch tells the story of Bangladesh's rich textile heritage.",
    price: 5200,
    compareAtPrice: 6000,
    stock: 4,
    categoryId: "cat-4",
    isFeatured: false,
    isBestSelling: false,
    status: "ACTIVE",
    sku: "NKK-003",
    tags: ["nakshi-katha", "peacock", "jamalpur"],
    createdAt: new Date("2024-04-10"),
    updatedAt: new Date("2024-04-10"),
    category: { id: "cat-4", name: "Nakshi Katha", slug: "nakshi-katha" },
    images: [
      { id: "img-11a", productId: "prod-11", imageUrl: "https://picsum.photos/seed/peacock-nakshi-11/600/600", sortOrder: 0, altText: "Peacock Nakshi Katha — Front" },
      { id: "img-11b", productId: "prod-11", imageUrl: "https://picsum.photos/seed/peacock-nakshi-11b/600/600", sortOrder: 1, altText: "Peacock Nakshi — Close-up" },
    ],
  },
  {
    id: "prod-12",
    title: "Nakshi Katha — Tree of Life",
    slug: "nakshi-katha-tree-of-life",
    description: "The iconic Tree of Life pattern embroidered with vibrant threads. A symbol of prosperity and family bonds, ideal as a home decor piece or meaningful gift.",
    price: 4800,
    compareAtPrice: 5500,
    stock: 7,
    categoryId: "cat-4",
    isFeatured: false,
    isBestSelling: false,
    status: "ACTIVE",
    sku: "NKK-004",
    tags: ["nakshi-katha", "tree-of-life", "home-decor"],
    createdAt: new Date("2024-04-15"),
    updatedAt: new Date("2024-04-15"),
    category: { id: "cat-4", name: "Nakshi Katha", slug: "nakshi-katha" },
    images: [
      { id: "img-12a", productId: "prod-12", imageUrl: "https://picsum.photos/seed/tree-nakshi-12/600/600", sortOrder: 0, altText: "Tree of Life Nakshi — Front" },
      { id: "img-12b", productId: "prod-12", imageUrl: "https://picsum.photos/seed/tree-nakshi-12b/600/600", sortOrder: 1, altText: "Tree of Life — Detail" },
    ],
  },

  /* ── Additional Chadar products (cat-2) ── */
  {
    id: "prod-13",
    title: "Silk-Blend Festive Chadar",
    slug: "silk-blend-festive-chadar",
    description: "A blend of silk and fine cotton, this festive chadar drapes beautifully and is perfect for Eid, weddings, and celebrations. Soft sheen with traditional motifs.",
    price: 2800,
    compareAtPrice: 3400,
    stock: 14,
    categoryId: "cat-2",
    isFeatured: false,
    isBestSelling: false,
    status: "ACTIVE",
    sku: "CHD-003",
    tags: ["chadar", "silk", "festive", "eid"],
    createdAt: new Date("2024-04-20"),
    updatedAt: new Date("2024-04-20"),
    category: { id: "cat-2", name: "Chadar", slug: "chador" },
    images: [
      { id: "img-13a", productId: "prod-13", imageUrl: "https://picsum.photos/seed/silk-chadar-13/600/600", sortOrder: 0, altText: "Silk Festive Chadar — Front" },
      { id: "img-13b", productId: "prod-13", imageUrl: "https://picsum.photos/seed/silk-chadar-13b/600/600", sortOrder: 1, altText: "Silk Chadar — Drape detail" },
    ],
  },
  {
    id: "prod-14",
    title: "Handloom Cotton Chadar — Checks",
    slug: "handloom-cotton-chadar-checks",
    description: "Classic check pattern woven on a traditional handloom. Versatile enough for daily wear or casual outings. Lightweight and easy to maintain.",
    price: 950,
    compareAtPrice: 1200,
    stock: 30,
    categoryId: "cat-2",
    isFeatured: false,
    isBestSelling: false,
    status: "ACTIVE",
    sku: "CHD-004",
    tags: ["chadar", "handloom", "checks", "daily-wear"],
    createdAt: new Date("2024-04-25"),
    updatedAt: new Date("2024-04-25"),
    category: { id: "cat-2", name: "Chadar", slug: "chador" },
    images: [
      { id: "img-14a", productId: "prod-14", imageUrl: "https://picsum.photos/seed/check-chadar-14/600/600", sortOrder: 0, altText: "Handloom Check Chadar — Front" },
      { id: "img-14b", productId: "prod-14", imageUrl: "https://picsum.photos/seed/check-chadar-14b/600/600", sortOrder: 1, altText: "Handloom Chadar — Texture" },
    ],
  },

  /* ── Additional Blanket products (cat-3) ── */
  {
    id: "prod-15",
    title: "Soft Fleece Throw Blanket",
    slug: "soft-fleece-throw-blanket",
    description: "Ultra-soft fleece throw blanket, perfect for cozy evenings. Machine washable, available in earthy Bangladeshi tones.",
    price: 1900,
    compareAtPrice: 2400,
    stock: 22,
    categoryId: "cat-3",
    isFeatured: false,
    isBestSelling: false,
    status: "ACTIVE",
    sku: "KMB-002",
    tags: ["blanket", "fleece", "throw"],
    createdAt: new Date("2024-05-01"),
    updatedAt: new Date("2024-05-01"),
    category: { id: "cat-3", name: "Blanket", slug: "kambal" },
    images: [
      { id: "img-15a", productId: "prod-15", imageUrl: "https://picsum.photos/seed/fleece-blanket-15/600/600", sortOrder: 0, altText: "Fleece Blanket — Front" },
      { id: "img-15b", productId: "prod-15", imageUrl: "https://picsum.photos/seed/fleece-blanket-15b/600/600", sortOrder: 1, altText: "Fleece Blanket — Folded" },
    ],
  },
  {
    id: "prod-16",
    title: "Traditional Khes Blanket",
    slug: "traditional-khes-blanket",
    description: "Woven from recycled cotton yarns using the centuries-old khes technique. Eco-friendly, durable, and reversible with different patterns on each side.",
    price: 2700,
    compareAtPrice: 3200,
    stock: 11,
    categoryId: "cat-3",
    isFeatured: false,
    isBestSelling: false,
    status: "ACTIVE",
    sku: "KMB-003",
    tags: ["blanket", "khes", "eco-friendly"],
    createdAt: new Date("2024-05-05"),
    updatedAt: new Date("2024-05-05"),
    category: { id: "cat-3", name: "Blanket", slug: "kambal" },
    images: [
      { id: "img-16a", productId: "prod-16", imageUrl: "https://picsum.photos/seed/khes-blanket-16/600/600", sortOrder: 0, altText: "Khes Blanket — Front" },
      { id: "img-16b", productId: "prod-16", imageUrl: "https://picsum.photos/seed/khes-blanket-16b/600/600", sortOrder: 1, altText: "Khes Blanket — Reverse side" },
    ],
  },
  {
    id: "prod-17",
    title: "Kids Cotton Blanket — Cartoon Print",
    slug: "kids-cotton-blanket-cartoon",
    description: "Bright, fun cartoon prints on soft cotton fabric. Safe for children, made without harmful dyes. A perfect companion for your little one's bedtime.",
    price: 1500,
    compareAtPrice: 1800,
    stock: 16,
    categoryId: "cat-3",
    isFeatured: false,
    isBestSelling: false,
    status: "ACTIVE",
    sku: "KMB-004",
    tags: ["blanket", "kids", "cotton", "cartoon"],
    createdAt: new Date("2024-05-08"),
    updatedAt: new Date("2024-05-08"),
    category: { id: "cat-3", name: "Blanket", slug: "kambal" },
    images: [
      { id: "img-17a", productId: "prod-17", imageUrl: "https://picsum.photos/seed/kids-blanket-17/600/600", sortOrder: 0, altText: "Kids Blanket — Front" },
      { id: "img-17b", productId: "prod-17", imageUrl: "https://picsum.photos/seed/kids-blanket-17b/600/600", sortOrder: 1, altText: "Kids Blanket — Pattern" },
    ],
  },

  /* ── Additional Muslin products (cat-5) ── */
  {
    id: "prod-18",
    title: "Dhaka Muslin Sari — Pure White",
    slug: "dhaka-muslin-sari-pure-white",
    description: "Woven from the finest Phuti Karpas cotton, this pure white Dhaka muslin sari is the pinnacle of Bangladeshi textile artistry. Exceptionally light and sheer.",
    price: 8500,
    compareAtPrice: 10000,
    stock: 3,
    categoryId: "cat-5",
    isFeatured: false,
    isBestSelling: false,
    status: "ACTIVE",
    sku: "MSL-002",
    tags: ["muslin", "sari", "dhaka", "white"],
    createdAt: new Date("2024-05-10"),
    updatedAt: new Date("2024-05-10"),
    category: { id: "cat-5", name: "Muslin", slug: "muslin" },
    images: [
      { id: "img-18a", productId: "prod-18", imageUrl: "https://picsum.photos/seed/muslin-sari-18/600/600", sortOrder: 0, altText: "Muslin Sari — Front" },
      { id: "img-18b", productId: "prod-18", imageUrl: "https://picsum.photos/seed/muslin-sari-18b/600/600", sortOrder: 1, altText: "Muslin Sari — Sheer detail" },
    ],
  },
  {
    id: "prod-19",
    title: "Muslin Kurta Fabric — 3 Yards",
    slug: "muslin-kurta-fabric-3yards",
    description: "3 yards of premium muslin fabric, ideal for stitching a kurta or panjabi. Breathable and incredibly soft against the skin.",
    price: 3200,
    compareAtPrice: 3900,
    stock: 20,
    categoryId: "cat-5",
    isFeatured: false,
    isBestSelling: false,
    status: "ACTIVE",
    sku: "MSL-003",
    tags: ["muslin", "fabric", "kurta"],
    createdAt: new Date("2024-05-12"),
    updatedAt: new Date("2024-05-12"),
    category: { id: "cat-5", name: "Muslin", slug: "muslin" },
    images: [
      { id: "img-19a", productId: "prod-19", imageUrl: "https://picsum.photos/seed/muslin-fabric-19/600/600", sortOrder: 0, altText: "Muslin Fabric — Rolled" },
      { id: "img-19b", productId: "prod-19", imageUrl: "https://picsum.photos/seed/muslin-fabric-19b/600/600", sortOrder: 1, altText: "Muslin Fabric — Texture" },
    ],
  },
  {
    id: "prod-20",
    title: "Muslin Scarf — Natural Beige",
    slug: "muslin-scarf-natural-beige",
    description: "A delicate muslin scarf in natural beige, hand-woven with a subtle stripe border. Lightweight enough to wear year-round.",
    price: 1800,
    compareAtPrice: 2200,
    stock: 13,
    categoryId: "cat-5",
    isFeatured: false,
    isBestSelling: false,
    status: "ACTIVE",
    sku: "MSL-004",
    tags: ["muslin", "scarf", "beige"],
    createdAt: new Date("2024-05-15"),
    updatedAt: new Date("2024-05-15"),
    category: { id: "cat-5", name: "Muslin", slug: "muslin" },
    images: [
      { id: "img-20a", productId: "prod-20", imageUrl: "https://picsum.photos/seed/muslin-scarf-20/600/600", sortOrder: 0, altText: "Muslin Scarf — Draped" },
      { id: "img-20b", productId: "prod-20", imageUrl: "https://picsum.photos/seed/muslin-scarf-20b/600/600", sortOrder: 1, altText: "Muslin Scarf — Texture" },
    ],
  },
];

export const dummyReviews = [
  {
    id: "rev-1",
    name: "Rahela Begum",
    title: "Exceptional quality product",
    rating: 5,
    content:
      "The katha I bought from Shilperhaat is truly outstanding. The handwork is so beautiful I could hardly believe it. Got full value for my money. The whole family loves it.",
    avatarUrl: null,
    role: "Dhaka, Bangladesh",
    isVisible: true,
    sortOrder: 1,
    createdAt: new Date("2024-03-01"),
    updatedAt: new Date("2024-03-01"),
  },
  {
    id: "rev-2",
    name: "Md. Karim Hossain",
    title: "Fast delivery and amazing packaging",
    rating: 5,
    content:
      "Received the product within just 2 days of ordering. The packaging was very nice. I bought the Nakshi Katha as a gift for my mother — she was absolutely delighted.",
    avatarUrl: null,
    role: "Chittagong, Bangladesh",
    isVisible: true,
    sortOrder: 2,
    createdAt: new Date("2024-03-05"),
    updatedAt: new Date("2024-03-05"),
  },
  {
    id: "rev-3",
    name: "Sumaiya Akter",
    title: "Most trusted online shop",
    rating: 4,
    content:
      "I've shopped from many places online, but I've never found a shop as trustworthy as Shilperhaat. Both the product quality and customer service are excellent. Will definitely buy again.",
    avatarUrl: null,
    role: "Rajshahi, Bangladesh",
    isVisible: true,
    sortOrder: 3,
    createdAt: new Date("2024-03-10"),
    updatedAt: new Date("2024-03-10"),
  },
  {
    id: "rev-4",
    name: "Tania Islam",
    title: "Best collection of traditional products",
    rating: 5,
    content:
      "I've never found such a beautiful collection of local handcrafts anywhere else. The skill and effort of the artisans is evident in every product. We should all support this kind of local craft.",
    avatarUrl: null,
    role: "Sylhet, Bangladesh",
    isVisible: true,
    sortOrder: 4,
    createdAt: new Date("2024-03-15"),
    updatedAt: new Date("2024-03-15"),
  },
  {
    id: "rev-5",
    name: "Abu Saeed",
    title: "Unmatched katha quality",
    rating: 5,
    content:
      "I bought the winter blanket and was amazed by the quality. You simply cannot find a product of this standard at this price anywhere else. Will be buying more for the whole family.",
    avatarUrl: null,
    role: "Khulna, Bangladesh",
    isVisible: true,
    sortOrder: 5,
    createdAt: new Date("2024-03-20"),
    updatedAt: new Date("2024-03-20"),
  },
];

export const dummyBanners = [
  {
    id: "ban-1",
    title: "Bangladesh's Finest Handcraft Textiles",
    subtitle: "Explore our vast collection of hand-woven Katha, Chadar & Blankets",
    imageUrl: "https://picsum.photos/seed/banner-textile-hero/1400/600",
    mobileImageUrl: "https://picsum.photos/seed/banner-textile-mobile/600/700",
    buttonText: "Shop Now",
    buttonLink: "/shop",
    sortOrder: 1,
    isActive: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "ban-2",
    title: "New Nakshi Katha Collection",
    subtitle: "Intricately hand-embroidered pieces by master artisans",
    imageUrl: "https://picsum.photos/seed/banner-nakshi-hero/1400/600",
    mobileImageUrl: "https://picsum.photos/seed/banner-nakshi-mobile/600/700",
    buttonText: "Explore",
    buttonLink: "/shop?category=nakshi-katha",
    sortOrder: 2,
    isActive: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
];

export const dummySiteSettings = {
  id: "settings-1",
  siteName: "Shilperhaat",
  logoUrl: null,
  faviconUrl: null,
  footerCopyright: "© 2025 Shilperhaat. All rights reserved.",
  whatsappNumber: "01700000000",
  socialLinks: {
    facebook: "https://facebook.com/shilperhaat",
    instagram: "https://instagram.com/shilperhaat",
  },
  deliveryCharge: 80,
  freeDeliveryMin: 2000,
  updatedAt: new Date("2024-01-01"),
};
